package org.example.People;

import org.example.Person;

public class Vendor extends Person {

    private String vendorType; //Type of vendor (food, drinks, tickets, gifts)
    private double revenue; // Revenue generated by the vendor

    public Vendor(String name, String vendorType) {
        super(name);
        this.vendorType = vendorType;
        this.revenue = 0.0; // Initial revenue is zero
    }
}
