package org.example.People;

import org.example.Person;
import org.example.Building;

public class Vendor extends Person {

    private String vendorType; //Type of vendor (food, drinks, tickets, gifts)
    private double revenue; // Revenue generated by the vendor

    public Vendor(String name, Building shopLocation) {
        super(name);
        this.location = shopLocation;
    }
}
